name: soonstays
description: "A new soonstays project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # https://pub.dev/packages/get
  get: ^4.7.3

  # https://pub.dev/packages/get_storage/versions
  get_storage: ^2.1.1

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1

  # https://pub.dev/packages/flutter_easyloading/versions
  flutter_easyloading: ^3.0.5

  # https://pub.dev/packages/dio
  dio: ^5.9.2

  # https://pub.dev/packages/chopper
  chopper: ^8.5.2

  # https://pub.dev/packages/http
  http: ^1.6.0

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.11.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2

  # https://pub.dev/packages/dotted_border
  dotted_border: ^3.1.0

  # https://pub.dev/packages/flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  # https://pub.dev/packages/readmore
  readmore: ^3.0.0

  # https://pub.dev/packages/gallery_zoom_slides
  gallery_zoom_slides: ^0.1.3

  # https://pub.dev/packages/intl
  intl: ^0.20.2

  # https://pub.dev/packages/pinput
  pinput: ^6.0.2

  # https://pub.dev/packages/shimmer
  shimmer: ^3.0.0

  # https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0

  # https://pub.dev/packages/share_plus
  share_plus: ^13.1.0

  # https://pub.dev/packages/geolocator
  geolocator: ^14.0.2

  # https://pub.dev/packages/razorpay_flutter
  razorpay_flutter: ^1.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  # https://pub.dev/packages/build_runner
  build_runner: ^2.15.0

  # https://pub.dev/packages/chopper_generator
  chopper_generator: ^8.6.2

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.13.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/social_media/
    - assets/images/investor/
    - assets/gif/
    - assets/images/appbar/
    - assets/images/login/
    - assets/images/profile/
    - assets/images/corporate/
    - assets/images/franchise/
    - assets/images/travel_agent/
    - assets/images/terms_conditions/
    - assets/images/legal_policy/
    - assets/images/splash/
    - assets/images/faq/
    - assets/images/contact_us/
    - assets/images/my_trips/
    - assets/images/property/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins_thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
    - family: Poppins_extraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
    - family: Poppins_light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: Poppins_regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins_medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins_semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins_bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins_extraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
